- roleId: 1
  roleName: "Admin"
  actions: 
  - showHomePage
  - deleteRentalExpense 
  - addExpenseRental
  - generateMOMPdfData
  - showMinutesOfMeeting
  - addMom
  - showCaptureMom
  - showBankReconciliationReport
  - showChangePassword
  - showShortcuts
  - showMaintenanceRegister
  - generateReceiptPDF
  - deleteGuestVehicle
  - addGuestVehicle
  - showAddGuestVehicle
  - showGuestVehicleEntry
  - deleteFlatTenant
  - addFlatTenant
  - showAddFlatTenant
  - showFlatTenantMapping
  - deleteMaintenence
  - addMaintenence
  - showAddMaintenence
  - showCollectMaintenence
  - deleteFlatOwner
  - addFlatOwner
  - showAddFlatOwner
  - showFlatOwnerMapping
  - showVehicleInformation
  - showVehicleSearch
  - showPersonMaster
  - showAddPerson
  - addPerson
  - deletePerson
  - showBlockMaster
  - showAddBlocks
  - addBlock
  - deleteblock
  - showVehicleMaster
  - showHomePage
  - showUserRoleMapping
  - showFlatMaster
  - showAddFlat
  - addFlat
  - deleteFlat
  - showShopMaster
  - showAddShop
  - addShop
  - deleteShop
  - showExpenseEntry
  - showAddExpense
  - addExpenseNew
  - deleteExpense
  - addVehicle
  - deleteVehicle
  - showAddVehicle
  - showIncomeEntry
  - showAddIncome
  - addIncome
  - addIncomeNew
  - deleteIncome
  - showAccountMasterNew
  - showAddAccount
  - addAccount
  - deleteAccount
  - getAmountForThisFlatType
  - showMaintenenceSummary
  - showFlatExceptionMaster
  - showAddFlatException
  - addFlatException
  - deleteFlatException
  - showMaintenenceMonthlyReport
  - showDistributionRegister
  - addDistribution
  - getFlatMasterByBlockId
  - showReport
  - showAddCollectTransferFees
  - addTransferFees
  - showTransferFeesRegister
  - generateTransferReceipt
  - deleteTransferId
  reports:
    - 1
  elements: 
    - 700187
    - 1
    - 21
    - 22
    - 2
    - 23
    - 3
    - 24
    - 25
    - 26
    - 27
    - 4
    - 28
    - 29
    - 5
    - 30
    - 31
    - 32
    - 33
    - 34
    - 50
    - 35
    - 36
    - 37
    - 38
    - 39
    - 40
    - 41
    - 42
    - 43
    - 44
    - 45